app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from debug_toolbar.toolbar import debug_toolbar_urls

from app import settings
from main.sitemaps import MotoSitemap, CategoryMotoSitemap 


# Sitemaps for SEO (Motorcycles and Categories)
sitemaps = {
    'moto': MotoSitemap,
    'cats': CategoryMotoSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="carts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("social-auth/", include("social_django.urls", namespace='social')),
    path("api/v1/", include("api_v1.urls", namespace="api_v1")),
    path("api/v1/drf-auth/", include('rest_framework.urls', namespace='rest_framework')),
    path("sitemap.xml/", sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('', include('django_prometheus.urls')),
]

# Debug toolbar and media file serving only in DEBUG mode
if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
"""
URL configuration for the 'orders' application.

Includes route for creating an order from the cart.
"""


from django.urls import path

from orders import views


app_name = 'orders'


urlpatterns = [
    path('create_order/', views.CreateOrderView.as_view(), name='create_order')
]

orders/models.py
from django.db import models


from catalog.models import Products
from users.models import User


class OrderitemQueryset(models.QuerySet):
    """
    Custom queryset for OrderItem to calculate total price and quantity."""

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    """
    Model representing a customer order.
    """

    user = models.ForeignKey(
        to=User, on_delete=models.SET_DEFAULT, verbose_name="User", default=None
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Order creation date"
    )
    phone_number = models.CharField(max_length=20, verbose_name="Phone number")
    requires_delivery = models.BooleanField(
        default=False, verbose_name="Delivery required"
    )
    delivery_address = models.TextField(
        null=True, blank=True, verbose_name="Delivery address"
    )
    payment_on_get = models.BooleanField(default=False, verbose_name="Cash on delivery")
    is_paid = models.BooleanField(default=False, verbose_name="Paid")
    status = models.CharField(
        max_length=50, default="Order in progress", verbose_name="Order status"
    )

    class Meta:
        db_table = "order"
        verbose_name = "Order"
        verbose_name_plural = "Orders"
        ordering = ("id",)

    def __str__(self):
        return (
            f"Order № {self.pk} | Customer {self.user.first_name} {self.user.last_name}"
        )


class OrderItem(models.Model):
    """
    Model representing a specific item in an order.
    """

    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Order")
    product = models.ForeignKey(
        to=Products,
        on_delete=models.SET_DEFAULT,
        null=True,
        verbose_name="Product",
        default=None,
    )
    name = models.CharField(max_length=150, verbose_name="Name")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Price")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Quantity")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Date of Sale"
    )

    class Meta:
        db_table = "order_item"
        verbose_name = "Sold product"
        verbose_name_plural = "Sold products"
        ordering = ("id",)

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

orders/forms.py
import re

from django import forms


class CreateOrderForm(forms.Form):
    """
    Form for creating a new order.

    Includes customer details, delivery options, and payment preferences.
    Validates phone number to ensure correct format.
    """
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
            ],
        )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", 'False'),
            ("1", 'True'),
            ],
        )

    def clean_phone_number(self):
        """
        Validates that the phone number contains only digits and is exactly 10 digits long.
        """
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Phone number must contain only digits")
        
        if not re.fullmatch(r"^\d{10}$", data):
            raise forms.ValidationError("Phone number must be exactly 10 digits long.")

        return data
    

orders/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import FormView

from carts.models import Cart
from orders.forms import CreateOrderForm
from orders.services.order_services import create_order_from_cart


class CreateOrderView(LoginRequiredMixin, FormView):
    """
    View for creating an order from the cart.

    This view allows authenticated users to create an order from the products
    in their cart. If the cart contains products, the order will be processed.
    If there is not enough stock, an error message will be displayed.
    """
    template_name = 'orders/create_order.html'
    form_class = CreateOrderForm
    success_url = reverse_lazy('users:profile')

    def get_initial(self):
        """
        Sets initial form data for first name and last name from the user's profile.
        """
        initial = super().get_initial()
        initial['first_name'] = self.request.user.first_name
        initial['last_name'] = self.request.user.last_name
        return initial

    def form_valid(self, form):
        """
        Handles the form submission if it is valid.
        Processes the cart and creates an order.
        If there is insufficient stock, raises a validation error.

        Args:
            form (CreateOrderForm): The valid form with user order data.

        Returns:
            HttpResponse: Redirect to the user's profile on success, or back to the form on failure.
        """
        try:
            # Using a transaction to ensure atomicity
            with transaction.atomic():
                user = self.request.user
                cart_items = Cart.objects.filter(user=user)

                if not cart_items.exists():
                    messages.error(self.request, 'Your cart is empty.')
                    return redirect('orders:create_order')

                order = create_order_from_cart(cart_items, form, user)

                if order:
                    messages.success(self.request, 'Order placed successfully!')
                    return redirect(self.success_url)
                else:
                    messages.error(self.request, 'There was an error processing your order.')
                    return redirect('orders:create_order')

        except ValidationError as e:
            messages.error(self.request, str(e))
            return redirect('orders:create_order')

    def form_invalid(self, form):
        """
        Handles the case when the form is invalid.
        Displays a message prompting the user to fill in all required fields.

        Args:
            form (CreateOrderForm): The invalid form.

        Returns:
            HttpResponse: Redirects the user back to the order creation page.
        """
        messages.error(self.request, 'Please fill in all required fields!')
        return redirect('orders:create_order')

    def get_context_data(self, **kwargs):
        """
        Adds additional context data for the order creation page.

        Args:
            **kwargs: Keyword arguments for context data.

        Returns:
            dict: Updated context with additional data for rendering the page.
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Order processing'
        context['order'] = True
        return context
        

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">Selected items</h3>
        <div class="container" id="cart-items-container">

            <!-- Cart items section -->
            {% user_carts request as carts %}
            {% include "carts/includes/included_cart.html" %}
        </div>
    </div>

    <!-- Order details section -->
    <div class="container">
        <h3 class="text-center">Order details</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url "orders:create_order" %}" method="post" id="create_order_form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Name*:</label>
                            <input type="text" class="form-control" id="id_first_name"
                            value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                            name="first_name" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                {% endif %}
                        </div>

                        <!-- Last Name -->
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Lastname*:</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name"
                            value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                            required>
                            {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                        </div>

                        <!-- Phone Number -->
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">Phone number*:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                            value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                placeholder="Enter your phone number in the format: XXX-XXX-XX-XX"
                                required>
                                {% if form.phone_number.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                                {% endif %}
                        </div>

                        <!-- Delivery Method -->
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">Delivery method: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="1" checked>
                                <label class="form-check-label" for="id_requires_delivery">Delivery required</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="0">
                                <label class="form-check-label" for="id_requires_delivery">In-store pickup</label>
                            </div>
                        </div>

                        <!-- Delivery Address -->
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">Delivery address*:</label>
                            <textarea class="form-control" id="id_delivery_address"
                                name="delivery_address" rows="2">{{ form.delivery_address.value|default:'' }}</textarea>
                                {% if form.delivery_address.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.delivery_address.errors}}</div>
                                {% endif %}
                        </div>

                        <!-- Payment Method -->
                        <div class="col-md-12 mb-3">
                            <label class="form-label">Payment method: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="0" checked>
                                <label class="form-check-label" for="id_payment_on_get">Card payment</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="1">
                                <label class="form-check-label" for="id_payment_on_get">Cash/Card on delivery</label>
                                {% if form.payment_on_get.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.payment_on_get.errors}}</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <!-- Submit Button -->
                    <button type="submit" class="btn btn-dark">Order</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock  %}