app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from debug_toolbar.toolbar import debug_toolbar_urls

from app import settings
from main.sitemaps import MotoSitemap, CategoryMotoSitemap 


# Sitemaps for SEO (Motorcycles and Categories)
sitemaps = {
    'moto': MotoSitemap,
    'cats': CategoryMotoSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="carts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("social-auth/", include("social_django.urls", namespace='social')),
    path("api/v1/", include("api_v1.urls", namespace="api_v1")),
    path("api/v1/drf-auth/", include('rest_framework.urls', namespace='rest_framework')),
    path("sitemap.xml/", sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('', include('django_prometheus.urls')),
]

# Debug toolbar and media file serving only in DEBUG mode
if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

orders/urls.py
"""
URL configuration for the 'orders' application.

Includes route for creating an order from the cart.
"""


from django.urls import path

from orders import views


app_name = 'orders'


urlpatterns = [
    path('create_order/', views.CreateOrderView.as_view(), name='create_order')
]

carts/models.py
from django.db import models

from catalog.models import Products
from users.models import User


class CartQueryset(models.QuerySet):
    """
    Custom queryset for the Cart model, providing utility methods
    for calculating total price and quantity across cart items.
    """

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    """
    Represents a cart item containing a product and its quantity,
    associated with either a user or an anonymous session.
    """

    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name="User"
    )
    product = models.ForeignKey(
        to=Products, on_delete=models.CASCADE, verbose_name="Product"
    )
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name="Quantity")
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Date added"
    )

    class Meta:
        db_table = "cart"
        verbose_name = "Cart"
        verbose_name_plural = "Carts"

    objects = CartQueryset().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        if self.user:
            return f"Cart{self.user.username} | Product {self.product.name} | Quantity {self.quantity}"
        return (
            f"Anonymous Cart | Product {self.product.name} | Quantity {self.quantity}"
        )

carts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views import View

from carts.mixins import CartMixin
from carts.services.cart_services import (
    add_product_to_cart,
    remove_product_from_cart,
    update_cart_item_quantity,
)
from catalog.models import Products


class CartAddView(CartMixin, View):
    """
    Add a product to the cart.

    If the product is already in the cart, the quantity is increased.
    If the product is not in the cart, a new cart item is created.
    """

    def post(self, request):
        product_id = request.POST.get("product_id")
        product = get_object_or_404(Products, id=product_id)

        add_product_to_cart(
            user=request.user if request.user.is_authenticated else None,
            session_key=(
                request.session.session_key
                if not request.user.is_authenticated
                else None
            ),
            product=product,
        )

        response_data = {
            "message": "Item added to cart",
            "cart_items_html": self.render_cart(request),
        }
        return JsonResponse(response_data)


class CartChangeView(CartMixin, View):
    """
    Change the quantity of a product in the cart
    """

    def post(self, request):
        cart_id = request.POST.get("cart_id")
        new_quantity = int(request.POST.get("quantity", 1))

        try:
            # Use the service to update the quantity
            update_cart_item_quantity(cart_id=cart_id, new_quantity=new_quantity)

            response_data = {
                "message": "Quantity updated",
                "quantity": new_quantity,
                "cart_items_html": self.render_cart(request),
            }

        except ValueError as e:
            response_data = {"message": str(e)}
            return JsonResponse(response_data, status=400)

        return JsonResponse(response_data)


class CartRemoveView(CartMixin, View):
    """
    Remove a product from the cart
    """

    def post(self, request):
        cart_id = request.POST.get("cart_id")

        try:
            # Use the service to remove the product
            remove_product_from_cart(cart_id)

            response_data = {
                "message": "Product removed from the cart",
                "cart_items_html": self.render_cart(request),
            }

        except ObjectDoesNotExist:
            response_data = {"message": "Cart item not found"}
            return JsonResponse(response_data, status=404)

        return JsonResponse(response_data)

carts/templates/carts/includes/included_cart.html
{% load static %}
{% load humanize %}


<div class="card mb-3 text-bg-light shadow-lg">
    {% for cart in carts %}
        <div class="card-header">
            <h5 class="card-title">{{ cart.product.name }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement"
                                    data-cart-id="{{ cart.id }}"
                                    data-cart-change-url="{% url "carts:cart_change" %}">
                                    {% csrf_token %}
                                    -</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ cart.quantity }}" readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment"
                                    data-cart-id="{{ cart.id }}"
                                    data-cart-change-url="{% url "carts:cart_change" %}">
                                    {% csrf_token %}
                                    +</button>
                            </span>
                        </div>
                    </div>
                    <div class="col p-0 m-0">
                        <p>x {{ cart.product.sell_price|intcomma }}</p>
                    </div>
                    <div class="col p-0">=</div>
                    <div class="col p-0"><strong> {{ cart.products_price|intcomma }} $</strong></div>
                    <div class="col p-0">
                        <a href="{% url "carts:cart_remove" %}" class="remove-from-cart"
                        data-cart-id="{{ cart.id }}">
                            {% csrf_token %}
                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                alt="Catalog Icon" width="16" height="16">
                        </a>
                    </div>
                </div>
            </li>
        </ul>
        {% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Total <strong>{{ carts.total_quantity }}</strong> product(s) cost</p>
        <h4 class="float-left"><strong>{{ carts.total_price|intcomma }} $</strong></h4>
    </div>
</div>
{% if carts and not order %}
<a class="btn btn-dark" href="{% url "orders:create_order" %}"> 
    Order
</a> 
{% endif %}