app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from debug_toolbar.toolbar import debug_toolbar_urls

from app import settings
from main.sitemaps import MotoSitemap, CategoryMotoSitemap 


# Sitemaps for SEO (Motorcycles and Categories)
sitemaps = {
    'moto': MotoSitemap,
    'cats': CategoryMotoSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="carts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("social-auth/", include("social_django.urls", namespace='social')),
    path("api/v1/", include("api_v1.urls", namespace="api_v1")),
    path("api/v1/drf-auth/", include('rest_framework.urls', namespace='rest_framework')),
    path("sitemap.xml/", sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('', include('django_prometheus.urls')),
]

# Debug toolbar and media file serving only in DEBUG mode
if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from catalog import views


app_name = 'catalog'


urlpatterns = [
    # Product category page
    path('<slug:category_slug>/', views.CatalogView.as_view(), name='category'),

    # Individual product detail page
    path('product/<slug:product_slug>/', views.ProductView.as_view(), name='product'),
    
    # Search results page (uses the same view as the catalog)
    path('search/', views.CatalogView.as_view(), name='search'),
]

users/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from users import views

app_name = 'users'

urlpatterns = [
    # Login view for users
    path('login/', views.UserLoginView.as_view(), name='login'),

    # User registration view
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),

    # User profile view
    path('profile/', views.UserProfileView.as_view(), name='profile'),

    # View to show the user's cart
    path('users-cart/', views.UserCartView.as_view(), name='users_cart'),

    # Logout view that redirects to main page after logout
    path('logout/', LogoutView.as_view(next_page='main:index'), name='logout'),

    # Password reset views
    path('password-reset/', 
        PasswordResetView.as_view(
            template_name = "users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
        ),
        name='password_reset'),

    path('password-reset/done/',
        PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
        name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
    template_name="users/password_reset_confirm.html",
    success_url=reverse_lazy("users:password_reset_complete")
    ),
    name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),

    # Password change views
    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),

    path ('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name='password_change_done'),
]

orders/models.py
from django.db import models


from catalog.models import Products
from users.models import User


class OrderitemQueryset(models.QuerySet):
    """
    Custom queryset for OrderItem to calculate total price and quantity."""

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    """
    Model representing a customer order.
    """

    user = models.ForeignKey(
        to=User, on_delete=models.SET_DEFAULT, verbose_name="User", default=None
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Order creation date"
    )
    phone_number = models.CharField(max_length=20, verbose_name="Phone number")
    requires_delivery = models.BooleanField(
        default=False, verbose_name="Delivery required"
    )
    delivery_address = models.TextField(
        null=True, blank=True, verbose_name="Delivery address"
    )
    payment_on_get = models.BooleanField(default=False, verbose_name="Cash on delivery")
    is_paid = models.BooleanField(default=False, verbose_name="Paid")
    status = models.CharField(
        max_length=50, default="Order in progress", verbose_name="Order status"
    )

    class Meta:
        db_table = "order"
        verbose_name = "Order"
        verbose_name_plural = "Orders"
        ordering = ("id",)

    def __str__(self):
        return (
            f"Order № {self.pk} | Customer {self.user.first_name} {self.user.last_name}"
        )


class OrderItem(models.Model):
    """
    Model representing a specific item in an order.
    """

    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Order")
    product = models.ForeignKey(
        to=Products,
        on_delete=models.SET_DEFAULT,
        null=True,
        verbose_name="Product",
        default=None,
    )
    name = models.CharField(max_length=150, verbose_name="Name")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Price")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Quantity")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Date of Sale"
    )

    class Meta:
        db_table = "order_item"
        verbose_name = "Sold product"
        verbose_name_plural = "Sold products"
        ordering = ("id",)

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    Custom user model extending Django's AbstractUser.

    Adds an optional profile image and phone number field.
    """
    image = models.ImageField(
        upload_to='users_images',
        blank=True,
        null=True,
        verbose_name='Avatar',
        help_text = 'User profile avatar'
    )
    phone_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        help_text = 'User phone number'
    )

    class Meta:
        db_table = 'user'
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

main/forms.py
from django import forms


class ContactForm(forms.Form):
    """
    A form for submitting a contact message.

    This form is designed to collect the user's first name, email address, 
    and message. It includes the necessary validation to ensure that the 
    fields are filled out correctly.
    """
    first_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form__input',
            'placeholder': 'Name'
        })
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form__input',
            'placeholder': 'E-mail'
        })
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form__textarea',
            'placeholder': 'Your text'
        })
    )

orders/forms.py
import re

from django import forms


class CreateOrderForm(forms.Form):
    """
    Form for creating a new order.

    Includes customer details, delivery options, and payment preferences.
    Validates phone number to ensure correct format.
    """
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
            ],
        )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", 'False'),
            ("1", 'True'),
            ],
        )

    def clean_phone_number(self):
        """
        Validates that the phone number contains only digits and is exactly 10 digits long.
        """
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Phone number must contain only digits")
        
        if not re.fullmatch(r"^\d{10}$", data):
            raise forms.ValidationError("Phone number must be exactly 10 digits long.")

        return data
    

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm

from users.models import User


User = get_user_model()

class UserLoginForm(AuthenticationForm):
    """
    Form for user login using Django's built-in authentication system.
    """
    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    """
    Custom user registration form extending Django's UserCreationForm.
    Ensures email uniqueness.
    """
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    def clean_email(self):
        """
        Check if email already exists in the database.
        """
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("This email already exists")
        return email


class ProfileForm(UserChangeForm):
    """
    User profile update form.
    """
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )


class UserPasswordChangeForm(PasswordChangeForm):
    """
    Form for changing user password with custom widget styling.
    """
    old_password = forms.CharField(
        label="Old password",
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )
    new_password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
        )

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView
from requests import session

from carts.models import Cart
from common.mixins import CacheMixin
from orders.models import Order, OrderItem
from users.forms import (
    ProfileForm,
    UserLoginForm,
    UserPasswordChangeForm,
    UserRegistrationForm
)


class UserLoginView(LoginView):
    """
    View for handling user login.
    Authenticates the user, assigns carts from session, and displays success message.
    """
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get_success_url(self):
        redirect_page = self.request.POST.get('next', None)
        if redirect_page and redirect_page != reverse('user:logout'):
            return redirect_page
        return reverse_lazy('main:index')
    
    def form_valid(self, form):
        session_key = self.request.session.session_key

        user = form.get_user()

        if user:
            auth.login(self.request, user)
            if session_key:
                # delete old authorized user carts
                forgot_carts = Cart.objects.filter(user=user)
                if forgot_carts.exists():
                    forgot_carts.delete()
                #add new authorized user carts from anonimous session
                Cart.objects.filter(session_key=session_key).update(user=user)

                messages.success(self.request, "You are logged in")

                return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Authorization'
        return context


class UserRegistrationView(CreateView):
    """
    View for handling user registration.
    Registers a new user, logs them in, assigns carts, and displays success message.
    """
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:profile')


    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.instance

        if user:
            form.save()
            auth.login(self.request, user)


        if session_key:
            Cart.objects.filter(session_key=session_key).update(user=user)

        messages.success(self.request, 'You have successfully registered and logged into your account')
        return HttpResponseRedirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Registration'
        return context


class UserProfileView(LoginRequiredMixin, CacheMixin, UpdateView):
    """
    View for displaying and updating user profile.
    Also shows the user's order history with related items.
    """
    template_name = 'users/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, "Profile updated successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "An error has occurred")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Profile'

        orders =  Order.objects.filter(user=self.request.user).prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product"),
                )
            ).order_by("-id")


        context['orders'] = self.set_get_cache(orders, f"user_{self.request.user.id}_orders", 60 * 2)
        return context


class UserCartView(TemplateView):
    """
    View for displaying the user's cart.
    """
    template_name = 'users/users_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Cart'
        return context


class UserPasswordChange(PasswordChangeView):
    """
    View for allowing the user to change their password.
    """
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Change password"}

users/templates/users/password_change_done.html
{% extends 'base.html' %}


{% block content %}
<h1>password changed successfully!</h1>

<p>You have successfully changed your password. <a class="change_pass_return" href="{% url 'users:profile' %}">Return to profile.</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content%}
<h1>Change password</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Change password</button></p>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Password changed</h1>
 
<p >Congratulations! You have successfully changed your account password. Use it to
  <a href="{% url 'users:login' %}">log in</a>.</p>
 
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{% load carts_tags %}
{% load humanize %}


{% block modal_cart %}{% endblock  %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- profile with user data -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Profile</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                    alt="User avatar" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "deps/images/baseavatar.jpg" %}"
                                    alt="User avatar" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name="image"
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Name*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Enter name" value="{{ form.first_name.value }}" required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Lastname*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                name="last_name"
                                placeholder="Enter lastname" value="{{ form.last_name.value }}" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Username*</label>
                                <input type="text" class="form-control" id="id_username"
                                name="username"
                                placeholder="Enter username" value="{{ form.username.value }}" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                name="email"
                                placeholder="Enter email *youremail@example.com" value="{{ form.email.value }}"
                                required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Save</button>
                    </form>
                </div>
            
            </div>



            <!-- Cart -->
            {% user_carts request as carts %}

            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Cart</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include "carts/includes/included_cart.html" %}
                        <!-- End of Cart -->
                    </div>
                </div>
            </div>


            <!-- Change password-->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <p class="text-center mb-4"><a href="{% url 'users:password_change' %}">Change password</a></p>
                </div>
            </div>

            <!-- Placed orders -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">My orders</h3>
                    <!-- Order markup -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Order № {{ order.id }} - {{ order.created_timestamp }} | Status: <strong class="mx-2">{{order.status}}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Product</th>
                                                    <th>Quantity</th>
                                                    <th>Price</th>
                                                    <th>Total cost</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url 'catalog:product' item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price|intcomma }}</td>
                                                    <td>{{ item.products_price|intcomma }}</td>
                                                    
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- End of order markup -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}


{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Registration</h2>
                <form action="{% url "user:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Name*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name"
                                placeholder="Enter your name" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Lastname*</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name"
                                placeholder="Enter your lastname" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Username*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                name="username"
                                placeholder="Enter your username" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                name="email"
                                placeholder="Enter your email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Password*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                name="password1"
                                placeholder="Enter password" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Password confirmation*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                name="password2"
                                placeholder="Confirm password" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Register</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock%}