app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from debug_toolbar.toolbar import debug_toolbar_urls

from app import settings
from main.sitemaps import MotoSitemap, CategoryMotoSitemap 


# Sitemaps for SEO (Motorcycles and Categories)
sitemaps = {
    'moto': MotoSitemap,
    'cats': CategoryMotoSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="carts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("social-auth/", include("social_django.urls", namespace='social')),
    path("api/v1/", include("api_v1.urls", namespace="api_v1")),
    path("api/v1/drf-auth/", include('rest_framework.urls', namespace='rest_framework')),
    path("sitemap.xml/", sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('', include('django_prometheus.urls')),
]

# Debug toolbar and media file serving only in DEBUG mode
if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from catalog import views


app_name = 'catalog'


urlpatterns = [
    # Product category page
    path('<slug:category_slug>/', views.CatalogView.as_view(), name='category'),

    # Individual product detail page
    path('product/<slug:product_slug>/', views.ProductView.as_view(), name='product'),
    
    # Search results page (uses the same view as the catalog)
    path('search/', views.CatalogView.as_view(), name='search'),
]

main/urls.py
from django.contrib import admin
from django.urls import path

from main import views


app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

users/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from users import views

app_name = 'users'

urlpatterns = [
    # Login view for users
    path('login/', views.UserLoginView.as_view(), name='login'),

    # User registration view
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),

    # User profile view
    path('profile/', views.UserProfileView.as_view(), name='profile'),

    # View to show the user's cart
    path('users-cart/', views.UserCartView.as_view(), name='users_cart'),

    # Logout view that redirects to main page after logout
    path('logout/', LogoutView.as_view(next_page='main:index'), name='logout'),

    # Password reset views
    path('password-reset/', 
        PasswordResetView.as_view(
            template_name = "users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done")
        ),
        name='password_reset'),

    path('password-reset/done/',
        PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"),
        name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
    template_name="users/password_reset_confirm.html",
    success_url=reverse_lazy("users:password_reset_complete")
    ),
    name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),

    # Password change views
    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),

    path ('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name='password_change_done'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% comment %} Meta tags {% endcomment %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% comment %} External font links from Google Fonts {% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
    href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
    rel="stylesheet">

    {% comment %} External stylesheets (Swiper for carousels) {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">
    
    {% comment %} Bootstrap and custom styles {% endcomment %}
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">

    {% comment %} Icons and Web App Manifest {% endcomment %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    
    {% comment %} Main custom stylesheet {% endcomment %}
    <link rel="stylesheet" href="{% static "style.css" %}">

    <title>{{ title }}</title>
</head>
<body>
    <div class="wrapper">
        {% comment %} Сommon header for all {% endcomment %}
        <header class="header {% block first_page_class %}{% endblock %}">
            <div class="container">
              <div class="header__inner">
                <a href="#" class="logo"><img src="{% static 'images/logo.png' %}" alt="" class="logo__img" width="100px" height="60px" /></a>
                <nav class="menu">
                  <button class="menu__btn">
                    <span></span>
                    <span></span>
                    <span></span>
                  </button>
                  <ul class="menu__list">
                    <li class="menu__list-item">
                      <a href="{% url 'main:index' %}" class="menu__list-link {% if request.path == '/' %}menu__list-link--active{% endif %}">HOME</a>
                    </li>

                    <li class="menu__list-item">
                      <a href="{% url "catalog:category" category_slug="husqvarna" %}" class="menu__list-link {% if is_catalog_active %}menu__list-link--active{% endif %}">PRODUCTS</a>
                    </li>

                    <li class="menu__list-item">
                      <a href="{% url "main:contact" %}" class="menu__list-link {% if request.path == '/contact/' %}menu__list-link--active{% endif %}">CONTACT US</a>
                    </li>

                    {% if not user.is_authenticated %}
                    <li class="menu__list-item">
                      <a href="{% url "user:login" %}" class="menu__list-link {% if request.path == '/user/login/' %}menu__list-link--active{% endif %}">SIGN IN</a>
                    </li>
                    {% else %}
                    <li class="menu__list">
                      <a href="{% url "user:profile" %}" class="menu__list-link {% if request.path == '/user/profile/' %}menu__list-link--active{% endif %}">PROFILE</a>
                    </li>

                    <li class="menu__list-item">
                      <a href="{% url "user:users_cart" %}" class="menu__list-link {% if request.path == '/user/users-cart/' %}menu__list-link--active{% endif %}">CART</a>
                    </li>

                    {% if user.is_staff %}
                    <li class="menu__list-item">
                      <a href="{% url "admin:index" %}" class="menu__list-link">ENTER FOR STAFF</a>
                    </li>
                    {% endif %}
                    <li class="menu__list-item">
                      <form action="{% url "user:profile" %}" method="get">
                      <button class="menu__list-link" style="background-color: transparent; border: none; color: white;" type="submit" class="menu_list-link">{{ user.username | truncatechars:5 }} </button>
                      </form>
                      <form action="{% url "user:logout" %}" method="post">
                        {% csrf_token %}
                        <button class="menu__list-link" style="background-color: transparent; border: none; color: white;" type="submit" class="menu_list-link"> | LOGOUT</button>
                      </form>
                    </li>
                    {% endif %}
                  <li>
                    {% block modal_cart %}
                    {% include "includes/cart_button.html" %}
                    {% endblock  %}
                  </li>
                  </ul>
                </nav>
              </div>
            </div>
          </header>

{% include "includes/notifications.html" %}
{% block content %}{% endblock  %}


        <footer class="footer">
            <div class="container">

                <nav class="footer__menu">
                    <ul class="footer__menu-list">
                        <li class="footer__menu-item">
                            <p class="footer__menu-title">Products</p>
                        </li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Used</a></li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">New</a></li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Sell your bike</a></li>
                    </ul>
                    <ul class="footer__menu-list">
                        <li class="footer__menu-item">
                            <p class="footer__menu-title">Resources</p>
                        </li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Blog</a></li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">FAQ</a></li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Contact us</a></li>
                    </ul>
                    <ul class="footer__menu-list">
                        <li class="footer__menu-item">
                            <p class="footer__menu-title">Work With TrueBike</p>
                        </li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Dealers</a></li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Partners</a></li>
                    </ul>
                    <ul class="footer__menu-list">
                        <li class="footer__menu-item">
                            <p class="footer__menu-title">About</p>
                        </li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">About us</a></li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Team</a></li>
                        <li class="footer__menu-item"><a href="#" class="footer__menu-link">Careers</a></li>
                    </ul>
                </nav>
                <ul class="app">
                    <li class="app__item">
                        <a href="#" class="app__item-link">
                            <img src="{% static "images/appstore.png" %}" alt="" class="app__item-img">
                        </a>
                    </li>
                    <li class="app__item">
                        <a href="#" class="app__item-link">
                            <img src="{% static "images/googleplay.png" %}" alt="" class="app__item-img">
                        </a>
                    </li>
                </ul>
                <div class="footer__copy">
                    <p class="footer__copy-text">
                        For questions about the TrueBike Buying Service please sell message to neologfly@gmail.com. <br>Images <a href="https://pixabay.com/ru/users/monoar_cgi_artist-2240009/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=6720610">Monoar Rahman Rony</a> from the site <a href="https://pixabay.com/ru//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=6720610">Pixabay</a>
                    </p>
                </div>
                <nav class="copy__nav">
                    <ul class="copy__nav-list">
                        <li class="copy__nav-item"><a href="#" class="copy__nav-link">Terms of Service</a></li>
                        <li class="copy__nav-item"><a href="#" class="copy__nav-link">Privacy Policy</a></li>
                    </ul>
                </nav>
            </div>
        </footer>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

    {% comment %} <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script> {% endcomment %}
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>

    {% comment %} <script src="{% static "deps/js/jquery-events.js" %}"></script> {% endcomment %}
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    
    <script src="{% static "/deps/js/main.js" %}"></script>
</body>
</html>